### ISSUE TITLE
Add support for Fitnesse web server launch

### ISSUE THREAD

**Issue by Nikscorp** [chrisotto6/VSCodeFitNesse#39]
**Proposal:**
Add option to launch just FitNesse server without `-c` option, in this case command `run test` should open default browser and launch selected test.

**Comment by chrisotto6** [comment]
This isn't what the -c option does, is this request to just launch the focused test in the fitnesse web client? If so that would need to be something completely different not using the run test functionality. That is explicitly for running the tests. 

Please review the command line arguments defined by FitNesse: http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.CommandLineArguments

**Comment by chrisotto6** [comment]
I need to investigate this. Putting to pipeline for now, it requires more changes than meets the eye.

**Comment by chrisotto6** [comment]
I don't think I'll ever get around to this, if you want to contribute it. By all means feel free.
