### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by mikeasage** [chrisotto6/VSCodeFitNesse#42]
When I run my test from within VS Code, the following command is run:

java -Xmx768m -jar C:\someLocation\testing\fitnesse\fitnesse-standalone.jar -p 8080 -d c:\FitNesse\ -c ?test^&format=text 

The end part of that seems malformed.  I'm guessing that should say 'test=' followed by the name of my test, but it's not outputting that way.  Thoughts?

**Comment by chrisotto6** [comment]
Hey @mikeasage are you by chance not using the default FrontPage in your FitNesse setup? What I think may be happening is that in order to run FitNesse from command line I need to determine the path from the front page to the actual test.

`// Chop down the returned string, we only care about FrontPage/to/TestName
        let test = path.slice(path.lastIndexOf("FrontPage"), path.search(/content.txt/gi) - 1);`

Issue #40 makes it so that the main page of FitNesse is configurable but it seems a couple months I never actually pushed that out in a release. Can you validate your current FitNesse configuration and let me know?
